//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.19 at 01:15:56 PM PDT 
//


package com.uciext.ws.hw4.service.model.orderconfirm;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.uciext.ws.hw4.service.model.orderconfirm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VendorCode_QNAME = new QName("", "vendorCode");
    private final static QName _ConfirmNumber_QNAME = new QName("", "confirmNumber");
    private final static QName _Price_QNAME = new QName("", "price");
    private final static QName _ProductSku_QNAME = new QName("", "productSku");
    private final static QName _OrderNumber_QNAME = new QName("", "orderNumber");
    private final static QName _OrderQuantity_QNAME = new QName("", "orderQuantity");
    private final static QName _TotalOrderPrice_QNAME = new QName("", "totalOrderPrice");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.uciext.ws.hw4.service.model.orderconfirm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrderConfirm }
     * 
     */
    public OrderConfirm createOrderConfirm() {
        return new OrderConfirm();
    }

    /**
     * Create an instance of {@link ProductConfirm }
     * 
     */
    public ProductConfirm createProductConfirm() {
        return new ProductConfirm();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vendorCode")
    public JAXBElement<String> createVendorCode(String value) {
        return new JAXBElement<String>(_VendorCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "confirmNumber")
    public JAXBElement<String> createConfirmNumber(String value) {
        return new JAXBElement<String>(_ConfirmNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "price")
    public JAXBElement<Double> createPrice(Double value) {
        return new JAXBElement<Double>(_Price_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "productSku")
    public JAXBElement<String> createProductSku(String value) {
        return new JAXBElement<String>(_ProductSku_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "orderNumber")
    public JAXBElement<String> createOrderNumber(String value) {
        return new JAXBElement<String>(_OrderNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "orderQuantity")
    public JAXBElement<Double> createOrderQuantity(Double value) {
        return new JAXBElement<Double>(_OrderQuantity_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "totalOrderPrice")
    public JAXBElement<Double> createTotalOrderPrice(Double value) {
        return new JAXBElement<Double>(_TotalOrderPrice_QNAME, Double.class, null, value);
    }

}
