
package com.uciext.ws.hw4.service.inventory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderServiceWS", targetNamespace = "http://inventory.service.hw4.ws.uciext.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderServiceWS {


    /**
     * 
     * @param order
     * @return
     *     returns com.uciext.ws.hw4.service.inventory.SubmitOrderResponse.Return
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitOrder", targetNamespace = "http://inventory.service.hw4.ws.uciext.com", className = "com.uciext.ws.hw4.service.inventory.SubmitOrder")
    @ResponseWrapper(localName = "submitOrderResponse", targetNamespace = "http://inventory.service.hw4.ws.uciext.com", className = "com.uciext.ws.hw4.service.inventory.SubmitOrderResponse")
    @Action(input = "http://inventory.service.hw4.ws.uciext.com/OrderServiceWS/submitOrderRequest", output = "http://inventory.service.hw4.ws.uciext.com/OrderServiceWS/submitOrderResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://inventory.service.hw4.ws.uciext.com/OrderServiceWS/submitOrder/Fault/Exception")
    })
    public com.uciext.ws.hw4.service.inventory.SubmitOrderResponse.Return submitOrder(
        @WebParam(name = "order", targetNamespace = "http://inventory.service.hw4.ws.uciext.com")
        Order order)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://inventory.service.hw4.ws.uciext.com", className = "com.uciext.ws.hw4.service.inventory.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://inventory.service.hw4.ws.uciext.com", className = "com.uciext.ws.hw4.service.inventory.HelloResponse")
    @Action(input = "http://inventory.service.hw4.ws.uciext.com/OrderServiceWS/helloRequest", output = "http://inventory.service.hw4.ws.uciext.com/OrderServiceWS/helloResponse")
    public String hello();

    /**
     * 
     * @param parameters
     * @return
     *     returns com.uciext.ws.hw4.service.inventory.CatalogResponse
     */
    @WebMethod
    @WebResult(name = "catalogResponse", targetNamespace = "http://inventory.service.hw4.ws.uciext.com", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://inventory.service.hw4.ws.uciext.com/OrderServiceWS/catalogRequest", output = "http://inventory.service.hw4.ws.uciext.com/OrderServiceWS/catalogResponse")
    public CatalogResponse catalog(
        @WebParam(name = "catalog", targetNamespace = "http://inventory.service.hw4.ws.uciext.com", partName = "parameters")
        Object parameters);

}
